### ISSUE TITLE
Mauvais schéma SQL

### ISSUE THREAD

**Issue by Aveys** [Aveys/Acupunctweb#1]
J'ai eu cette petite erreur : 

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'firstname' in 'field list'' in /Users/arthurveys/TLI/Acupunctweb/lib/model/user.php:73 Stack trace: #0 /Users/arthurveys/TLI/Acupunctweb/lib/model/user.php(73): PDOStatement->execute() #1 /Users/arthurveys/TLI/Acupunctweb/lib/control/action.php(79): user_create('fofox', 'art', 'vey', 'test@test.fr', 'test', 'test') #2 /Users/arthurveys/TLI/Acupunctweb/lib/control/action.php(27): signup() #3 {main} thrown in /Users/arthurveys/TLI/Acupunctweb/lib/model/user.php on line 73
```

Ca doit venir de la BDD qui est pas à jour sur les tables.
J'ai mis un fichier init.sql qui permet de créer notre DB, tu peux le completer avec ta table users ?

**Comment by nicolasanjoran** [comment]
Je vais m'occuper de ça.

Nicolas Anjoran

**Comment by Aveys** [comment]
Closed with 5419eba18f71ec298403171e47a29a5e5b9a7b6d
